version: '3'
services:
  frontend:    
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    # working_dir: /home/node/app
    # volumes:
    #   - ./:/home/node/app
    #   - node_modules:/home/node/app/node_modules
    restart: always
